version: "3"
services:
    # app: # サービス名
    #     build: . # ①ビルドに使うDockerfileの場所
    #     volumes:
    #         - ./app:/go/src/app # ③マウントディレクトリ

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        ports:
            - '3308:3306'
        command: --default-authentication-plugin=mysql_native_password
